<?= $this->doctype() ?>

<html lang="tr">
    <head>
        <meta charset=utf-8" />
        <meta name="keywords" content="Veri topla, Veri topla, form oluştur, bilgi topla, online anket ,analiz et, raporla, işletmeler, fabrikalar, üniversiteler, kurumlar" />

        <?= $this->headTitle('Online Form Widget')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->appendStylesheet($this->basePath('/bootstrap/css/bootstrap.min.css'))

        ?>

        <!-- Scripts -->

    </head>
    <body class="hold-transition skin-green-light sidebar-mini">
    <div class="wrapper">

        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div style="height: 30px;">
                  <ol class="breadcrumb">
                   <?= $this->pageBreadcrumbs()->render(); ?>
                </ol>
                </div>
               
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-12 col-md-12 col-xs-12">
                        <div class="box">
                           
                            <!-- /.box-header -->
                            <div class="box-body">
                                <?= $this->content ?>
                                <hr>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <p>&copy; <?= date('Y') ?> <a href="https://ekokod.com">ekoKod.com</a> by Erkin AKA</p>
        </footer>
        </div>
        <?= $this->inlineScript()?>

    </body>
</html>
